# config.yaml
app_name: CKJAPAN-LLTS
site_name: ST5L
sftp:
  host: 3.1.186.221
  port: 22
  username: cfg-admin
  password: Cfg@123@
  remote_path: LLTS/Upload/
usrp:
  sampling_rate: 2e6 # 2 MHz
  center_freq: 100e6 # 100 MHz
  gain: 0
  adc_voltage_range: 1 # [-1,1] Volts peak-to-peak
data_path: D:\CKJAPAN-LLTS\Data\
segment_path: D:\CKJAPAN-LLTS\Segment_Data\
record_time: 1 # second
trigger_level: 100 # mV